# Generated by Django 5.0.4 on 2024-04-22 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadosMedico',
        ),
    ]
